version: "3.9"

services:

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/vortex
      - REDIS_URL=redis://redis:6379

  worker:
    build: .
    command: celery -A celery_app worker --loglevel=info
    depends_on:
      - redis
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/vortex
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:7

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: vortex
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
